# Generated by Django 2.0.7 on 2019-03-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prsn_of_contact', models.CharField(max_length=60, verbose_name='Person of Contact')),
                ('tel_number', models.CharField(max_length=14, verbose_name='Telephone Number')),
                ('location', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=3)),
                ('num_of_employees', models.IntegerField(default=1, verbose_name='Number of Employees')),
            ],
        ),
    ]
