# Generated by Django 2.0.7 on 2019-03-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=60)),
                ('number', models.CharField(max_length=14)),
                ('location', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=3)),
                ('employees', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ('employees',),
            },
        ),
    ]
